# Generated by Django 5.1 on 2024-11-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="books_bought",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="books_sold",
            field=models.IntegerField(default=0),
        ),
    ]
