# Generated by Django 5.1 on 2024-11-10 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_genre_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
