# Generated by Django 5.1 on 2024-11-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0006_alter_user_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="edition",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="books",
            name="pages",
            field=models.IntegerField(),
        ),
    ]
