# Generated by Django 5.1 on 2024-11-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0007_alter_books_edition_alter_books_pages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
        migrations.RenameIndex(
            model_name="book",
            new_name="baseapp_boo_id_358e69_idx",
            old_name="baseapp_boo_id_4fbf35_idx",
        ),
        migrations.RenameIndex(
            model_name="book",
            new_name="baseapp_boo_name_23660b_idx",
            old_name="baseapp_boo_name_881922_idx",
        ),
        migrations.RenameIndex(
            model_name="book",
            new_name="baseapp_boo_created_01aa2c_idx",
            old_name="baseapp_boo_created_d5258f_idx",
        ),
    ]
