# Generated by Django 5.1 on 2024-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0008_rename_books_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="edition",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(),
        ),
    ]
