# Generated by Django 5.1 on 2024-11-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0009_alter_book_edition_alter_book_pages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genre",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="baseapp_cat_name_ccc701_idx",
            old_name="baseapp_gen_name_64ed56_idx",
        ),
    ]
