# Generated by Django 5.1 on 2024-11-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0010_rename_genre_category_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="category",
        ),
    ]
