# Generated by Django 5.1 on 2024-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0011_rename_genre_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("N", "Almost New"), ("U", "Used"), ("R", "Readable")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/%Y/%m/%d"),
        ),
    ]
